export const WorkData = [
    {
        id: 1,
        title: "Peep × Triptii Dimri",
        slug: "peep-triptii-dimri",
        description: "Capital and celebrity, timed to give the round visible runway and fund the campaign that followed.",
        engagement: "Fundraise + Brand Ambassador",
        category: "Beauty",
        scope: "12 months • Active",
        services: [
            "Capital",
            "Talent",
            "Strategy"
        ],
        detailHeading: "Two moves, structured as one.",
        descArray: [
            "Capital and celebrity, timed to give the round visible runway and fund the campaign that followed.",
            "We led the fundraise for Peep and onboarded Triptii Dimri as the face of the brand in the same window. The ambassador signing was timed to give the round visible runway. The round was sized to fund the campaign that followed.",
            "Peep walked away with the working capital to scale and a brand ambassador whose audience maps cleanly onto the category.",
        ],
        image: "/images/work/brand-peep.png",
        classname: "bg-[#E1DFD2]",
    },
    {
        id: 2,
        title: "KAAI × Tiger Shroff",
        slug: "kaai-tiger-shroff",
        description: "Performance, energy and aspiration, fused into a single signing that gives the brand both scale and depth.",
        engagement: "Strategic Advisory + Brand Ambassador",
        category: "Fashion • Performance",
        scope: "Ongoing advisory",
        services: [
            "Strategy",
            "Talent",
            "brand",
        ],
        detailHeading: "Mass-premium reach, anchored to a strategic seat.",
        descArray: [
            "Performance, energy and aspiration, fused into a single signing that gives the brand both scale and depth.",
            "For KAAI, we serve as strategic advisors and brought Tiger Shroff on as brand ambassador. Tiger’s positioning, performance, energy and mass-premium reach gives KAAI both scale and aspiration in a single signing.",
            "Our advisory mandate covers the broader brand build: how to deploy the ambassador across content, campaigns and channel partnerships so the equity created translates into measurable category share.",
        ],
        image: "/images/work/brand-kaai.png",
        classname: "bg-[#1F3352]",
    },
    {
        id: 3,
        title: "House of Trudy’s × Athiya Shetty",
        slug: "house-of-trudys-athiya-shetty",
        description: "Quiet luxury mapped to a strategic anchor for product, retail and narrative.",
        engagement: "Strategic Advisory + Brand Ambassador",
        category: "Fashion • Quiet Luxury",
        scope: "Ongoing advisory",
        services: [
            "Strategy",
            "Talent",
            "brand",
        ],
        detailHeading: "A considered fit, not a stunt signing.",
        descArray: [
            "Quiet luxury mapped to a strategic anchor for product, retail and narrative.",
            "We came in as strategic advisors to The House of Trudy’s and onboarded Athiya Shetty as brand ambassador. The fit was deliberate. Athiya’s personal brand of considered, quiet luxury maps cleanly onto where Trudy’s sits in the market.",
            "Beyond the signing, we shaped the brand narrative around the partnership so the ambassador wasn’t just a face, but a strategic anchor for everything from product launches to retail conversations.",
        ],
        image: "/images/work/brand-trudys.png",
        classname: "bg-[#EBE2D9]",
    },
    {
        id: 4,
        title: "Sports Stadium",
        slug: "sports-stadium",
        description: "A full-stack engagement: capital first, then the ongoing work to make sure that capital compounds.",
        engagement: "Fundraise + Brand Ambassador",
        category: "Sports • Retail",
        scope: "Long-term advisory",
        services: [
            "Capital",
            "Strategy",
            "brand",
        ],
        detailHeading: "Capital in the door. Then a long-term seat at the table.",
        descArray: [
            "A full-stack engagement: capital first, then the ongoing work to make sure that capital compounds.",
            "For Sports Stadium, we acted as both fundraising partner and ongoing strategic advisor. We helped shape the investment thesis, brought the right investors to the table, and stayed on as advisors through the rollout.",
            "The advisory work covers category positioning, brand architecture and growth strategy. Capital first, then the ongoing work to make sure that capital actually compounds.",
        ],
        image: "/images/work/brand-sports-stadium.png",
        classname: "bg-[#000000]",
    },
];